### ISSUE TITLE
403 after email verification

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_ui#1]
Date: March 25, 2021, 10:00 am ET
Browser: Chrome, Version 89.0.4389.114 (Official Build) (x86_64)
Error code: 403
Page url: /accounts/verify/

Details since I deleted my screen capture: 
When registering, I went to my email to verify it, clicked the link, and it opened a new window, so my email was verified. Returning to the original registration window, I entered my email to resend verification, and got the 403 Forbidden:

"Forbidden (403)
CSRF verification failed. Request aborted.

More information is available with DEBUG=True."

@birbjam -- updated 4/4 with as much as info as I have per error reporting guide!

**Comment by birbjam** [comment]
So I don't think much can be done here. Once the email is verified, there is no need to re-enter email to get a verification link since that whole process has been completed. Maybe what we can add to the `verify` page is a "if you've already verified your email, you can now close this window" kind of message.
