### ISSUE TITLE
Duplication of status options on community project

### ISSUE THREAD

**Issue by corrieroe** [biocodellc/localcontexts_ui#17]
**Date and Time:** May 22, 2:50 pm ET

**Which browser & version are you using?** Chrome, 90.0.4430.212 

**What was the error code?** n/a

**Which page had the error and what were you doing when it happened? Be as detailed as possible.** 
The Activity page on a community account (Northeast Nation), looking at a project and setting its status. In the dropdown menu to select the project's status, there are two sets of the answers. (see attached screenshot) This is true before and after selecting the status. There can only be one status selected at any time, and it defaulted to the bottom set of answers once saved, even if selecting from the top.

I have not seen this issue with other projects, and this is the only one in my list that was sent to multiple communities, so perhaps it is connected to that. The status dropdown on the second community (Community of the Southwest) did not have this issue, and did not reflect the status chosen by first community.

**Screenshot or screen recording if possible.** See below, these two shots show before selecting the status and after.
<img width="1292" alt="Double status menu before selecting" src="https://user-images.githubusercontent.com/49764220/119238248-68145a80-bb0f-11eb-8182-3c4d50a1b5f2.png">
<img width="1274" alt="Double status menu with selection" src="https://user-images.githubusercontent.com/49764220/119238249-68acf100-bb0f-11eb-844b-a9831ce466f2.png">

**Comment by birbjam** [comment]
So it looks like this is happening because in TKNotice, under "statuses" two statuses were created for Northeast Nation. I wonder if this was because community was notified more than once by whoever created the project? Good catch Corrie, I'll fix this to make sure each community is only notified once.

<img width="941" alt="Screen Shot 2021-05-24 at 10 15 00 AM" src="https://user-images.githubusercontent.com/41635757/119384127-15ef4880-bc79-11eb-8d64-03444188d189.png">

**Comment by birbjam** [comment]
This should be fixed now, since communities can only be notified of a particular project once, it should prevent another status from being created.
